name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          fetch-tags: false
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npx corepack enable pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm oxlint
      - run: pnpm run typecheck
      - uses: apple-yagi/test-scope@v0.0.1
        id: test_scope
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - if: steps.test_scope.outputs.affected_tests != ''
        run: pnpm run test ${{ steps.test_scope.outputs.affected_tests }}
      - run: pnpm run build
