name: CI

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  ci:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
          fetch-tags: false
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npx corepack enable pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm oxlint
      - run: pnpm run typecheck
      - uses: apple-yagi/affogato@v0.0.3
        id: affogato
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - if: steps.affogato.outputs.affected_tests != ''
        run: pnpm run test ${{ steps.affogato.outputs.affected_tests }}
      - run: pnpm run build
